# directory path to where Elite: Dangerous stores its journals on your system. 
# For example, on my system: "/home/user/.local/share/Steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved Games/Frontier Developments/Elite Dangerous/"
elite_dangerous_journal_path = ""

# if on Linux, "Pyperclip" library may cause "focus stealing" (especially on Wayland) for now. To remedy this, EDSST can use a different clipboard utility
# In that case I recommend to use: https://github.com/YaLTeR/wl-clipboard-rs
wl_copy_bin_path = ""