[project]
name = "elite-stellar-survey-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyperclip>=1.11.0",
    "watchfiles>=1.1.1",
]
